### ISSUE TITLE
What are these hard-coded values in line 55?

### ISSUE THREAD

**Issue by anjali-shrivastava** [Davi-Schumacher/KS-2Samp-PySparkSQL#2]
https://github.com/Davi-Schumacher/KS-2Samp-PySparkSQL/blob/0a494b488554275565e1de3c0ed9474669a6342d/ks_2samp_sparksql.py#L55

**Comment by saiprasadcrown** [comment]
+1, I have similar question

**Comment by Davi-Schumacher** [comment]
The short answer is this was a blind copy from https://github.com/scipy/scipy/blob/v0.14.0/scipy/stats/stats.py#L3809-L3889, which was scipy's implementation of the 2 sample KS test back when I wrote this. If I had to guess, they are values that are calculated to perform a clever approximation in order to save some computation.

Take a look at the newer implementation https://github.com/scipy/scipy/blob/v1.8.0/scipy/stats/_stats_py.py#L7275-L7449. You may want to try converting this newer implementation to be compatible with Spark.
