### ISSUE TITLE
Code copied for PySpark training

### ISSUE THREAD

**Issue by josefernandezest98** [Davi-Schumacher/KS-2Samp-PySparkSQL#3]
Hi, I have copied your code for a free PySpark course, into the Machine Learning Exercise 2 section. Maybe I´ll change something to fit better with my code. Anyway, I put the link to your repository and your github account. Thanks you very much, it was a great help! Here you are the link if you want to check: https://github.com/josefernandezest98/training/blob/main/PySpark_Training/pyspark_training_notebook.ipynb

**Comment by Davi-Schumacher** [comment]
@josefernandezest98 please feel free to use this, that's why I posted it. The scipy ks-test code I used here has been updated since the time I wrote this years ago, and it's not necessarily robust, just gives the overall idea. If you have any ideas on how to improve it as you work with it please contribute so others can benefit as well.

**Comment by josefernandezest98** [comment]
Great! Thank you so much Davi
